# Generated by Django 2.2 on 2019-04-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_exchangeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeform',
            name='calculated_value',
            field=models.IntegerField(default=''),
        ),
    ]
