# Generated by Django 2.2 on 2019-04-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190426_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeform',
            name='calculated_value',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
