# Generated by Django 2.2 on 2019-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190426_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeform',
            name='amount_to_exchange',
            field=models.CharField(max_length=20),
        ),
    ]
