# Generated by Django 2.2 on 2019-04-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190426_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeform',
            name='calculated_value',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
